on:
  push:
    branches: [ master ]

name: Deploy to Azure App service

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
        submodules: recursive


    - name: Azure login
      env:
        azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        subscription_id: ${{ secrets.SUBSCRIPTON_ID }}
      run: |
        az login --service-principal -u $azure_client_id -p $azure_client_secret --tenant $azure_tenant_id
        az account set --subscription $subscription_id


    - name: ACR login
      env:
        docker_server_url: ${{ secrets.AZURE_DOCKER_SERVER_URL_STAGING }}
        docker_server_username: ${{ secrets.AZURE_DOCKER_SERVER_USERNAME_STAGING }}
        docker_server_password: ${{ secrets.AZURE_DOCKER_SERVER_PASSWORD_STAGING }}
      run: |
        docker login $docker_server_url --username $docker_server_username --password $docker_server_password


    - name: Docker build and push to ACR
      env:
        docker_server_url: ${{ secrets.AZURE_DOCKER_SERVER_URL_STAGING }}
        docker_image_name: ${{ secrets.AZURE_DOCKER_IMAGE_NAME_STAGING }}
        docker_file_path: ${{ secrets.AZURE_DOCKER_FILE_PATH }}
        tag: ${{ github.sha }}
        github_pat: ${{ secrets.GIT_ACCESS_TOKEN }}
      run: |
        docker build -t $docker_server_url/$docker_image_name:latest .
        docker build -t $docker_server_url/$docker_image_name:$tag .
        docker push $docker_server_url/$docker_image_name:latest
        docker push $docker_server_url/$docker_image_name:$tag
        

    - name: Deploy to App service
      env:
        docker_server_url: ${{ secrets.AZURE_DOCKER_SERVER_URL_STAGING }}
        docker_image_name: ${{ secrets.AZURE_DOCKER_IMAGE_NAME_STAGING }}
        tag: ${{ github.sha }}
        resource_group: ${{ secrets.AZURE_RESOURCE_GROUP_STAGING }}
        app_service: ${{ secrets.AZURE_APP_SERVICE_STAGING }}

      run: |
        az webapp config container set --docker-custom-image-name $docker_server_url/$docker_image_name:$tag --name $app_service --resource-group $resource_group
